name: CI

# Trigger: hvornår skal denne workflow køre?
on:
  push:
    branches: [ "main" ]        
  pull_request:
    branches: [ "main" ]         

jobs:
  build:
    # Runner: hvilket operativsystem GitHub Actions skal bruge til at køre jobbet
    runs-on: ubuntu-22.04

    steps:
    # Hent kildekoden fra repositoriet ned på runneren - færdiglavet fra github marketplace
    - uses: actions/checkout@v4

    # Installer den ønskede .NET SDK-version på runneren
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x             # x = nyeste version i håb om senest sikkerhedsrettelser

    # Læser og henter NuGet pakker som projektet afhænger af
    - name: Restore dependencies
      run: dotnet restore

    # Kompilér løsningen — --no-restore springer restore over da det allerede er gjort
    - name: Build
      run: dotnet build --no-restore

    # Kør alle xUnit-tests
    # --no-build springer kompilering over da build allerede er udført
    - name: Test
      run: dotnet test --no-build --verbosity normal